yt_a/urls.py
from django.contrib import admin
from django.urls import path
from yt_site import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # slash after port number is not considered here.Start writing stuff which follows it.
    path('', views.home, name='home'),#For first page,ip:port/
    path('page/<page_number>', views.home, name='home'),
    # path('^image/(\d+)',views.image_serve,name='image_serve') #When img src="/image/hash"
    path('image/<hash_of_image>',views.image_serve,name='image_serve'),#hash_of_image keyword args
    path('upload/',views.upload_file,name='upload_file'),
    path('search/',views.search,name='search')
    ]

yt_site/models.py
from django.db import models

# Create your models here.

yt_site/forms.py
from django import forms

class tags_image_form(forms.Form):
	# If you don't give label,var name with 1st letter caps  becomes label.
	# Eg tags==> "Tags:" with a colon in the end
	tags = forms.CharField(max_length=100)
	raw_image = forms.FileField(label='Select Image')

yt_site/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
# . importing from this folder.In django,if modules are in same folder,simply importing doesn't work
from . import db_handle 
from . import redis_handle
from . import image_handle
from .forms import tags_image_form
'''
	image_handle does both tags and image
'''
def upload_file(request):
	# if file uploaded,below if statement will be true
	# https://www.javatpoint.com/django-file-upload
	if request.method == 'POST' and request.FILES['raw_image']:
		form_data=tags_image_form(request.POST,request.FILES)
		# Once is_valid is done,data is available in form_data.cleaned_data
		if form_data.is_valid():
			raw_image = request.FILES['raw_image']
			filename=raw_image.name
			# if filename already there,name will be changed.To get original file name from disk,see handle_uploaded_image func.
			raw_tags=form_data.cleaned_data['tags']
			print(raw_tags)
			upload_status=handle_uploaded_image(raw_image,raw_tags)
			return render(request, 'upload_done.html', {'filename': filename,'upload_status':upload_status})
	tags_image_form_=tags_image_form()
	return render(request, 'upload_file.html',{'tags_image_form_':tags_image_form_})


def handle_uploaded_image(raw_image_uploaded,raw_tags):
	print("handling ",raw_image_uploaded.name)
	fs = FileSystemStorage()
	file_name_in_disk=fs.save(raw_image_uploaded.name, raw_image_uploaded)
	return image_handle.aspectRatioResize(raw_image_uploaded.name,raw_tags)

def home(request,page_number=None):
	if page_number==None:
		content={'page_number':'1'}
		return render(request,'index.html',content)
	else:
		hashes_and_tags=[]
		hashes_and_tags=db_handle.get_n_image_hashes_and_tags(page_number)
		page_number=int(page_number)+1
		hashes_len=len(hashes_and_tags)
		if(hashes_len==0):
			return render(request,"not_found.html")
		elif (hashes_len<10 and hashes_len>0):
			page_number=0#Preventing next page link from being shown
		content={'page_number':page_number,'hashes_and_tags':hashes_and_tags}
		return render(request,'images.html',content)

def search(request):
	print(request)

def image_serve(request,hash_of_image):
	image_data=redis_handle.get_from_redis_feed(hash_of_image)
	if image_data==None:
		print(hash_of_image+"not found")
		return HttpResponse(image_data, content_type="image/png")
	else:
		return HttpResponse(image_data, content_type="image/png")

templates/f.html
{% for value in e %}
    <p>{{ value }}</p>
{% endfor %}

templates/images.html
<link rel="shortcut icon" href="/static/favicon.ico">
<title>Image Page</title>
<style type="text/css">
	.button {
		background-color: #f44336;
		border: none;
		color: white;
		padding: 15px 32px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		border-radius: 8px;
	}
</style>


{% for hash_and_tag in hashes_and_tags %}
	<img src="/image/{{hash_and_tag.0}}" />
	<br>
	<i>Tags:</i>
	<b>#{{hash_and_tag.1}}</b>
	<b>#{{hash_and_tag.2}}</b>
	<b>#{{hash_and_tag.3}}</b>
	<b>#{{hash_and_tag.4}}</b>
	<b>#{{hash_and_tag.5}}</b>
	<br>
	<br>
	<br>
{% endfor %}

<a href="/upload/"><button class="button">Upload</button></a>
{%if page_number > 0 %}
	<a href="/page/{{page_number}}"><button class="button" style="background-color: green;">{{page_number}}</button></a>
{% else %}
	<p>You have reached the last page</p>
{%endif%}

templates/index.html
<title>This is the intro page</title>
<link rel="shortcut icon" href="/static/favicon.ico">
<style type="text/css">
	.button {
		background-color: #f44336;
		border: none;
		color: white;
		padding: 15px 32px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		border-radius: 8px;
	}
</style>
<h1>This is the intro page guys</h1>
<a href="/upload/"><button class="button">Upload</button></a>
<a href="/page/{{page_number}}"><button class="button" style="background-color: green;">Click to view images</button></a>

templates/not_found.html
<img src="/static/404.png" alt="not_found">

templates/search.html
<link rel="shortcut icon" href="/static/favicon.ico">

templates/simple_upload.html
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

{% endblock %}

templates/upload_done.html
<title>File uploaded success</title>


{%if upload_status == True %}
	<h1>File {{filename}} uploaded successfully!</h1>
{% else %}
	<h1>File {{filename}} is not a valid image or it already exists</h1>
{%endif%}
<a href="/">Click to go to home page!</a>

templates/upload_file.html
<link rel="shortcut icon" href="/static/favicon.ico">
<style type="text/css">
	#id_tags,#id_raw_image {
		background-color: #f44336;
		border: none;
		color: white;
		padding: 15px 32px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		border-radius: 8px;
	}
</style>

{% load static %}

{% block content %}
  <form method="post" autocomplete="off" enctype="multipart/form-data">
  	<!-- autocomplete="off".So that,when you click browser back button,old from value won't be shown -->
  	<!-- DND  csrf_token.Necessary for file uploads.To prevent csrf attacks.DND-->
    {% csrf_token %} 
    {{ tags_image_form_ }}
    <!-- <input type="file" name="raw_image"> -->
    <input type="submit" value="upload!"></input>
  </form>
{% endblock %}

templates/upload_test.html
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

templates/uplod_file.html
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

{% endblock %}